import { Footer, Nav } from '@/components'
import './globals.css'
import localFont from "next/font/local";
import { Roboto } from "next/font/google";
import { Poppins } from "next/font/google";
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-poppins",
});
const bernier = localFont({
  src: "../public/assets/font/BERNIER™ Regular.ttf",
});


export const metadata = {
  title: 'Dar Djaj',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${poppins.variable} ${bernier.variable} bg-[#0B0E11] text-white`}>

        {children}
        <Footer />
      </body>
    </html>
  )
}
